// Alerts
export const SET_ALERT = "SET_ALERT";
export const SET_ALERT_IN_FORM = "SET_ALERT_IN_FORM";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
// Section
export const SET_SECTION = "SET_SECTION";
export const SET_REDIRECT = "SET_REDIRECT";
// Articles
export const ARTICLE_LOADING_START = "ARTICLE_LOADING_START";
export const ARTICLE_LOADING_END = "ARTICLE_LOADING_END";
export const LOAD_USER_ARTICLES_SUCCESS = "LOAD_USER_ARTICLES_SUCCESS";
export const LOAD_USER_ARTICLES_FAIL = "LOAD_USER_ARTICLES_FAIL";
export const LOAD_FOCUS_ARTICLE_SUCCESS = "LOAD_FOCUS_ARTICLE_SUCCESS";
export const LOAD_FOCUS_ARTICLE_FAIL = "LOAD_FOCUS_ARTICLE_FAIL";